[pytest]
asyncio_mode = auto
testpaths = tests
python_files = *_test.py
pythonpath = .
addopts = -v -s --cov=app --cov-report=html
filterwarnings =
    ignore:.*datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning:mongomock.*
